# Generated by Django 5.2 on 2025-12-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=50)),
                ('book_author', models.CharField(blank=True, max_length=400)),
                ('book_price', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
