# Generated by Django 5.2.4 on 2025-07-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomjoke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
