# Generated by Django 5.2.7 on 2025-10-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10)),
                ('gmail', models.EmailField(blank=True, max_length=254)),
                ('uucms_num', models.CharField(max_length=15)),
                ('rno', models.IntegerField()),
                ('photo', models.ImageField(null=True, upload_to='studentphoto/')),
            ],
        ),
    ]
